using System.Text.Json.Nodes;
using Anthill.Core.Common;
using Anthill.Core.Configuration;
using Anthill.Core.Domain;
using Anthill.Core.Native;

namespace Anthill.Core.Pheromones;

/// <summary>
/// Mission success scoring. The arithmetic is delegated to the native C++ kernel
/// (<see cref="NativeKernel.ScoreMission"/>) — one of the hot paths the hybrid split
/// targets — with a bit-identical managed fallback. Quality flags (builder bonus,
/// verifier verdict) are derived here in managed code where the text lives.
/// </summary>
public sealed class PheromoneEngine
{
    public const int QualityBonusThreshold = 1500;

    public double ScoreMission(Mission mission)
    {
        var total = mission.Tasks.Count;
        if (total == 0) return 0.0;
        var completed = mission.Tasks.Count(t => t.Status == TaskStatus.Complete);
        var failed = mission.Tasks.Count(t => t.Status == TaskStatus.Failed);
        var skipped = mission.Tasks.Count(t => t.Status == TaskStatus.Skipped);

        var builderResults = mission.Tasks
            .Where(t => (t.AssignedAnt is "builder" or "coder") && !string.IsNullOrEmpty(t.Result))
            .Select(t => t.Result!);
        var builderBonus = string.Join("\n", builderResults).Length > QualityBonusThreshold;

        var verifierResults = mission.Tasks
            .Where(t => t.AssignedAnt == "verifier" && !string.IsNullOrEmpty(t.Result))
            .Select(t => t.Result!);
        var verdict = TextUtil.ExtractVerdict(string.Join("\n", verifierResults));
        var verdictCode = verdict switch { "failed" => -1, "needs_improvement" => 0, "passed" => 1, _ => 2 };

        return NativeKernel.ScoreMission(total, completed, failed, skipped, builderBonus, verdictCode);
    }
}

/// <summary>
/// Parses a coder ant's JSON response into a validated <see cref="PatchSet"/>. Enforces
/// the safe-path contract, content truncation, and the requires-approval invariant, exactly
/// as the Python <c>PatchProposalParser</c> did. Throws on structurally invalid input.
/// </summary>
public sealed class PatchProposalParser
{
    /// <summary>
    /// Turn the coder's structured output into a patch set.
    /// </summary>
    /// <param name="readCurrent">
    /// Reads a workspace file's CURRENT contents, or null when it does not exist. v0.3.8.57.
    ///
    /// THE GAP THIS CLOSES. `PatchProposal.BaseHash` was assigned in exactly one place in the whole
    /// codebase — `WorkspaceChangeSet`, which derives proposals from a finished workspace diff. The
    /// coder path produced none, so every model-authored modify, delete and rename carried a null
    /// base hash, and `PatchApply`'s stale-base check — the largest item in AUTONOMY-10 Phase 1,
    /// shipped in v0.3.8.37 — could not fire on the one path that actually needed it. The guard was
    /// real, tested, and unreachable for the patches it was built for.
    ///
    /// Stamped HERE rather than at apply time, and that is the point: the hash must record the bytes
    /// the coder REASONED ABOUT, which is the state at production. Computing it during apply would
    /// hash whatever the file says by then and always agree with itself.
    ///
    /// Optional because a caller with no workspace — the parser's own tests, a replay over stored
    /// text — has nothing to read. Those proposals keep a null hash and are handled exactly as
    /// pre-v0.3.8.57 ones are: verifiable in a sandbox, refused by the live applier.
    /// </param>
    public PatchSet Parse(string rawText, string missionId, string taskId,
        Func<string, string?>? readCurrent = null)
    {
        var parsed = Json.ExtractJsonObject(rawText);
        var summary = (parsed["summary"]?.GetValue<string>() ?? "").Trim();
        if (summary.Length == 0) summary = "Structured patch proposal generated by CoderAnt.";

        if (parsed["proposals"] is not JsonArray rawProposals)
            throw new ArgumentException("'proposals' must be a list.");

        var proposals = new List<PatchProposal>();
        foreach (var item in rawProposals.Take(AnthillRuntime.MaxPatchProposalsPerSet))
        {
            if (item is not JsonObject obj) continue;
            // Parse each proposal independently: one malformed entry (a placeholder path, a missing
            // reason) shouldn't discard the valid proposals alongside it in the same set.
            try
            {
                var filePath = Validation.ValidateSafePatchPath((obj["file_path"]?.GetValue<string>() ?? "").Trim());
                var changeType = (obj["change_type"]?.GetValue<string>() ?? "modify").Trim().ToLowerInvariant();
                var reason = (obj["reason"]?.GetValue<string>() ?? "").Trim();
                var risk = (obj["risk"]?.GetValue<string>() ?? "").Trim();
                // GetValue<string>() throws on JSON null nodes — must check ValueKind first
                var oldContent = JsonStrOrNull(obj["old_content"]);
                var newContent = JsonStrOrNull(obj["new_content"]);
                if (oldContent is not null) oldContent = TextUtil.Truncate(oldContent, AnthillRuntime.MaxPatchContentChars, "...[old_content truncated]");
                if (newContent is not null) newContent = TextUtil.Truncate(newContent, AnthillRuntime.MaxPatchContentChars, "...[new_content truncated]");
                if (reason.Length == 0) reason = "No reason provided by the coder.";
                if (risk.Length == 0) risk = "Unspecified risk. Human review required.";

                // v0.3.8.56 (field report): a model that PARROTS the prompt's example produced no
                // proposal. Two junk approval cards reached the operator's chat whose new_content
                // was the template's own placeholder sentence continued with prose ("Proposed new
                // content for Anthill.cs, considering retrying cloning…"). The echo is rejected by
                // its exact opening words — a narrow, named guard, not a prose classifier.
                if (EchoesTemplate(newContent, "Proposed new content")
                    || EchoesTemplate(oldContent, "Exact old content"))
                    continue;

                var parsedChangeType = EnumExtensions.ParsePatchChangeType(changeType);

                // v0.3.8.57 — stamp the base hash for the operations that destroy prior state.
                //
                // `add` is exempt by construction: it creates a file, so there is no prior state it
                // could have been built against, and hashing a target that should not exist would
                // record a fact about the wrong thing. A read that comes back null (the file is not
                // there) also leaves the hash null — the applier refuses that as a missing target,
                // which names the real problem better than a hash of nothing would.
                string? baseHash = null;
                if (readCurrent is not null
                    && parsedChangeType is PatchChangeType.Modify or PatchChangeType.Delete or PatchChangeType.Rename)
                {
                    var current = readCurrent(filePath);
                    if (current is not null) baseHash = PatchApply.HashOf(current);
                }

                proposals.Add(new PatchProposal
                {
                    FilePath = filePath, ChangeType = parsedChangeType, Reason = reason,
                    Risk = risk, OldContent = oldContent, NewContent = newContent, BaseHash = baseHash,
                    RequiresApproval = true, Status = PatchStatus.Proposed,
                });
            }
            catch { /* skip the malformed proposal, keep the rest */ }
        }
        return new PatchSet { MissionId = missionId, TaskId = taskId, Summary = summary, Proposals = proposals };
    }

    /// <summary>The prompt-template echo test: content that OPENS with the example's own words is
    /// the example, not a change. Narrow on purpose — it matches the template's exact openings.</summary>
    private static bool EchoesTemplate(string? content, string opening) =>
        content is not null && content.TrimStart().StartsWith(opening, StringComparison.OrdinalIgnoreCase);

    // Returns string value or null for both missing keys and explicit JSON null values.
    private static string? JsonStrOrNull(System.Text.Json.Nodes.JsonNode? node)
    {
        if (node is null) return null;
        if (node is System.Text.Json.Nodes.JsonValue v &&
            v.GetValueKind() == System.Text.Json.JsonValueKind.Null) return null;
        try { return node.GetValue<string>(); } catch { return null; }
    }
}
